name: Project Branches Watcher

on:
  create:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  handle-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read package.json (if exists)
        id: pkg
        run: |
          NAME=""
          DESC=""

          if [ -f package.json ]; then
            NAME=$(jq -r '.name // empty' package.json)
            DESC=$(jq -r '.description // empty' package.json)
          fi

          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "desc=$DESC" >> $GITHUB_OUTPUT

      - name: Call backend to create/delete project
        env:
          API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          API_URL="https://projects.do-code.com/projects"
          EVENT="${{ github.event_name }}"
          NAME="${{ steps.pkg.outputs.name }}"
          DESC="${{ steps.pkg.outputs.desc }}"

          if [[ "$EVENT" == "create" ]]; then
            DATA="{\"branch\": \"$BRANCH_NAME\""
            if [[ -n "$NAME" ]]; then
              DATA="$DATA, \"name\": \"$NAME\""
            fi
            if [[ -n "$DESC" ]]; then
              DATA="$DATA, \"description\": \"$DESC\""
            fi
            DATA="$DATA}"

            curl -X POST "$API_URL" \
              -H "Authorization: Bearer $API_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$DATA"

          elif [[ "$EVENT" == "delete" ]]; then
            curl -X DELETE "$API_URL/$BRANCH_NAME" \
              -H "Authorization: Bearer $API_TOKEN"
          fi
